### PR TITLE
Add support for local button icons

### PR DESCRIPTION
**Pull request by ssawchenko**
Added fix in firefox template code to allow us to easily include local resource image files as the button icon.

### CODE REVIEW

**Comment by reicolina** [comment]
Looking into this...please don't merge yet

**Comment by reicolina** [comment]
@ssawchenko: i think openForge provides a method to get the 'url' for an unqualified path (i.e local file). From their tools library:

``` javascript
    /**
     * Resolve this name to a fully-qualified local or remote resource.
     * The resource is not checked for existence.
     * This method does not load the resource. For that, use "getPage()".
     *
     * For example, unqualified name: "my/resource.html"
     * On Chrome: "chrome-extension://djggepjbfnnmhppnebibkbomfmnmkjln/my/resource.html"
     *
     * @param {string} resourceName Unqualified resource.
     * @param {function(string)=} success Response data
     * @param {function({message: string}=} error
     */
    'getURL': function(resourceName, success, error) {
        internal.priv.call("tools.getURL", {
            name: resourceName.toString()
        }, success, error);
    }
```

Maybe it is worth to try this first?

**Comment by ssawchenko** [comment]
getURL is asynchronous (using callbacks) whereas setResourceIcon is not. I am not sure if this matters or not (I am guessing it doesn't matter), but I will give it a try.

**Comment by reicolina** [comment]
Closing without merging as it turns out that forge.tools.getURL does the job.

**Pull request closed without merging**
