### PR TITLE
Fix BE-490 - BE popup does not display when clicking BE toolbar icon after opening a new tab and closing an old tab

### PR DESCRIPTION
**Pull request by dle-pi**
A) Issue: BE popup does not display when clicking BE toolbar icon after opening a new tab and closing an old tab
1) Root Cause:
The m_activeProcessId value is not right. It doesn't hold the processId value of the active tab.
2) Solution:
Using Windows functions to find window of the active tab, then get the processId value of the active tab.

B) Issue: opening 4 tabs, close 3 first tabs and click BE icon, no BE popup displays
1) Root cause:
In 4 tabs, there are 2 tabs that have the same processId. So when closes 3 first tabs, the m_clientListeners map for the processId of the tab 4th is also erased, so it does not exist anymore and causes the BE couldn't open the popup.

2) Solution:
Because there isn't 1:1 mapping between tab and process, as we see above two tabs have the same processId, so we have to use another way for mapping to satisfy 1:1 mapping.

I found that there is an 1:1 mapping between tab and the HWND of the tab, so I use this mapping to get proxy information for the HWND of the active tab

### CODE REVIEW

**Comment by irytir** [comment]
Code which tries to find IE window by name/class needs to be aware of these things:
- different IE versions have different internal windows structure/hierarchy, have you tested this on all supported IE versions?
- what if there are two IE windows opened, will this still find the correct window/pid ?

**Comment by dle-pi** [comment]
- The solution that finds IE window by name/class has been tested and passed on IE 8, 9, 10, 11
- If there are two IE windows opened, this will still find the correct window/pid, because the active window will be the first item return by the FindWindowEx function.

**Comment by dle-pi** [comment]
@irytir 
In the new commit, I have fix another issue relating to BE-490 as below. And in this fix, I also fix the BE-231 issue that the popup is shown on wrong window when there are two IE windows opened.

Fix issue relating to BE490 - opening 4 tabs (close 3 first tabs and click BE icon, no BE popup displays)
1) Root cause:
In 4 tabs, there are 2 tabs that have the same processId. So when closes 3 first tabs, the m_clientListeners map for the processId of the tab 4th is also erased, so it does not exist anymore and causes the BE couldn't open the popup.

2) Solution:
Because there isn't 1:1 mapping between tab and process, as we see above two tabs have the same processId, so we have to use another way for mapping to satisfy 1:1 mapping.

I found that there is an 1:1 mapping between tab and the HWND of the tab, so I use this mapping to get proxy information for the HWND of the active tab

**Comment by irytir** [comment]
You cannot rely on the fact that the active window will be the first item return by the FindWindowEx(). This is not how it is documented in the MSDN for the NULL as the first argument:

_The function searches among windows that are child windows of the desktop_
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633500(v=vs.85).aspx

If you get the right window handle on your system then you may be lucky. We need more deterministic solution.

**Comment by dle-pi** [comment]
In the document https://msdn.microsoft.com/en-us/library/windows/desktop/ms633500(v=vs.85).aspx, it says:
- If hwndParent is NULL, the function uses the desktop window as the parent window. The function searches among windows that are child windows of the desktop.
  - If hwndChildAfter is NULL, the search begins with the first child window of hwndParent.

It means that if both hwndParent and hwndChildAfter are NULL, the search begins with the first child window of the desktop window, because the desktop window is considered as the parent window.

My code is 
     HWND  currentIE = ::FindWindowEx(NULL, NULL, L"IEFrame", NULL);
will get the first child window of the desktop window that has the class name is "IEFrame", or we can say that it will return the active IE window, because the first child window is exactly the active window ( you can check that by using Spy++). So it will return the active window of the Internet Explorer.

**Comment by irytir** [comment]
You assume that the first child window is the active window. Its not documented behavior so it may not be the case, even tough it seems to work for you. I would say add also a check that the first child "IEFrame" window is actually the active one (using GetForegroundWindow() or similar). If it's not then loop through other "IEFrame" windows to find the active one to use.

**Comment by dle-pi** [comment]
By MSDN https://msdn.microsoft.com/en-us/library/windows/desktop/ms632599(v=vs.85).aspx says that: 
"An active window is the top-level window of the application with which the user is currently working. To allow the user to easily identify the active window, the system places it at the top of the z-order and changes the color of its title bar and border to the system-defined active window colors. Only a top-level window can be an active window. When the user is working with a child window, the system activates the top-level parent window associated with the child window."

Do you agree that the first child window is the top-level window? If not, please review the link 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms632599%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#zorder
that says: 
"Z-Order
The z-order of a window indicates the window's position in a stack of overlapping windows. This window stack is oriented along an imaginary axis, the z-axis, extending outward from the screen. The window at the top of the z-order overlaps all other windows. The window at the bottom of the z-order is overlapped by all other windows."

About GetForegroundWindow(), I think a foreground and background window have nothing to do with active windows, it has to do with threading, as you can see from https://msdn.microsoft.com/en-us/library/windows/desktop/ms632599(v=vs.85).aspx#foreground says:
"Foreground and Background Windows
Each process can have multiple threads of execution, and each thread can create windows. The thread that created the window with which the user is currently working is called the foreground thread, and the window is called the foreground window. All other threads are background threads, and the windows created by background threads are called background windows."

**Comment by irytir** [comment]
All these articles explain how windows are structured and layered logically in z-order but it does not tell us how the FindWindowEx algorithm searches through the windows. If you look at the Spy++ output you will see that there are many windows above the IEFrame ones in the list, so first child window is not the top-level window (or right-click at the top Desktop window in Spy++ and in Properties->Windows tab you will see First Child Window listed is not IEFrame).

Anyway, I created a test app to verify your findings and it does seem the Windows rearranges the order of the returned window handles so the active IEFrame comes first. To move this forward I would say we can live with it for now, as it is better solution than before. We can revisit if we hit a problem when this does not work.

**Pull request merged**
